### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JackyDaniels** [oskopek/javaanpr#80]
Hello . 

I have an issue with that error :
Exception in thread "main" java.io.IOException: Couldn't find parser syntax description file
	at Parser.<init>(Parser.java:43)
	at Intelligence.<init>(Intelligence.java:33)
	at Main.main(Main.java:109)

I tried with moving syntax.xml in every one of the other folders , change values and ect.Bbut it still comes out as an error . Can you help me please ?

**Comment by oskopek** [comment]
Hi, how are you running your main application? What is the working directory you're running it from?

**Comment by JackyDaniels** [comment]
I am using eclipse for java code. I create project , write code and than use the Run option to run it . Every single class is in the directory of the project.

**Comment by oskopek** [comment]
That still leaves a lot of options for how the project is set up. Try to use maven to run the project: `mvn exec:java` and change the main() method in Main.

**Comment by oskopek** [comment]
Closing due to inactivity.
